name: .NET

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore MiniMikuDanceMaui/MiniMikuDanceMaui.csproj
      - name: Build
        run: dotnet build MiniMikuDanceMaui/MiniMikuDanceMaui.csproj --configuration Release --no-restore
      - name: Run unit tests
        run: dotnet test Tests/AppCore.Tests/AppCore.Tests.csproj --verbosity normal
        continue-on-error: true
